# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:00:36+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import RootModel


class Emojis(RootModel[Any]):
    root: Any


class Hashtags(RootModel[Any]):
    root: Any


class Images(RootModel[Any]):
    root: Any


class Instagram(RootModel[Any]):
    root: Any


class LinkShortening(RootModel[Any]):
    root: Any


class Tags(RootModel[List]):
    root: List
